import Head from 'next/head'
import { Inter } from '@next/font/google'
import { BsFillMoonStarsFill, BsFillSunFill, BsLinkedin, BsGithub } from 'react-icons/bs'
import{AiFillInstagram} from 'react-icons/ai'
import Skills from './components/Skills'
import Works from './components/Works'
import Awards from './components/Awards'
import { useState } from 'react'
import Spline from '@splinetool/react-spline';
import Contact from './components/Contact'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkMode, setDarkMode] = useState(false);
  const darkModeHandler = () => {
    if (darkMode) {
      return 'dark:bg-gray-900 text-white'
    } else {
      return 'bg-white text-black'
    }
  }
  const about_me = "I'm an AI enthusiastic. Fell in love with DL during Engg. time and since then tryng to explore DL world to the fullest. I have a 3+ years of experience as a Data Analyst in Finance domain (Microsoft - Incentive Compensation) in TCS"
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="/styles/globals.css"/>
        {/*<script src="https://cdn.tailwindcss.com"></script>*/}
      </Head>
      <main className={'divide-y  px-10 font-serif '+ darkModeHandler()}>
        <section className='min-h-screen'>
          <nav className='py-8 flex justify-between'>
            <h1 className='text-xl'><b>Portfolio</b></h1>
            <ul className='flex items-center'>
              <li>
                { (darkMode) ? <BsFillSunFill className='cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)}/> : <BsFillMoonStarsFill className='cursor-pointer text-2xl' onClick={() => setDarkMode(!darkMode)}/>}
              </li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href='https://docs.google.com/document/d/e/2PACX-1vSAlGJOyrg36Vb7hOr6F_4DjG6VpT9hTn9_gc3igpxvUHHjCtCFBIGPUEiJdF1I737EOtzjFshpQr7g/pub'>Resume</a></li>
            </ul>
          </nav>
            <div className='relative h-80 m-0'>
            <Spline scene="https://prod.spline.design/TdPk-iQ6ALSw6KJL/scene.splinecode" />
           {/* <Image src={ me } /> */ }
          </div>
          <div className='text-center pb-5'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'><b>Pratik Davidson</b></h2>
            <p>{about_me}</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 pb-10 text-gray-600'>
            <a href='https://www.linkedin.com/in/pratik-davidson-107732215/'><BsLinkedin className='cursor-pointer'/></a>
            <a href='https://github.com/PratikDavidson'><BsGithub className='cursor-pointer'/></a>
            <a href='https://www.instagram.com/pratik_davidson/'><AiFillInstagram className='cursor-pointer'/></a>
          </div>
        </section>
        <Skills />
        <Works />
        <Awards />
        <Contact />
        </main>
    </>
  )
}
